# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a `Student` object.
#'
#' Constructes a `Student` object with non-default values and accesses
#' their favorite numbers.
#'
#' @return
#' An `integer` vector containing the student's favorite numbers.
#'
#' @export
simulate_student <- function() {
    .Call(`_RcppStudent_simulate_student`)
}

